blueprint:
  name: Android Actionable Notification
  description: >-
    A script that sends an actionable notification to Android devices with up to 3 actionable buttons.
  domain: script
  source_url: https://github.com/home-assistant/core/blob/919f4dd719ac2551ca63a93780852bba1aadd7b0/homeassistant/components/script/blueprints/confirmable_notification.yaml
  input:
    notify_device:
      name: Notification service
      description: Notification service name (ex. Notify.mobile_app_....). Note that device/s needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
    title:
      name: "Title"
      description: "The title of the button shown in the notification."
      default: ""
      selector:
        text:
    message:
      name: "Message"
      description: "The message body"
      selector:
        text:
    icon:
      name: (Optional) Icon
      description: MDI Icon to use for notification such as mdi:cctv Leaving blank will use the Home Assistant icon.
      default: ''
      selector:
        icon:
    color:
      name: (Optional) Color - Android Specific
      description: Color for icon. Can be color name or hex value. Leaving blank will use the Home Assistant blue.
      default: [3, 169, 244]
      selector:
        color_rgb:      
    priority:
      name: Notification Priority - Android Specific
      description: Priority level for notification
      default: 'default'
      selector:
        select:
          mode: dropdown
          options:
            - high
            - low
            - max
            - min
            - default
    sticky:
      name: (Optional) Sticky - Android Specific
      description: When enabled, the notification will stay active on the device after interacting with it and remain there until cleared.
      default: false
      selector:
        boolean: {}
    channel:
      name: (Optional) Channel - Android Specific
      description: Create a new channel for notifications to allow custom notification sounds, vibration patterns and overide of Do Not Disturb mode. Configured directly on the device.
      default: ''
      selector:
        text:
    tag:
      name: "Notification Tag"
      description: "notification tag for updating and dismissing the notification"
      default: ''
      selector:
        text:
    timeout:
        name: "Timeout duration"
        default: {}
        selector:
          duration:
    image:
      name: "Image"
      description: "Path to optional image to attach with message"
      default: {}
      selector:
        text:
    click_action:
      name: Click Action
      description: What to open when the notification is clicked. Can be a URL, a relative URL to your Home Assistant instance such as /lovelace/test, or an Android application such as app://<package_name>. 
      default: ''
      selector:
        text:
    confirm_text:
      name: "Confirmation Text"
      description: "Text to show on the confirmation button"
      default: "Confirm"
      selector:
        text:
    confirm_action:
      name: "Confirmation Action"
      description: "Action to run when notification is confirmed"
      default: []
      selector:
        action:
    dismiss_text:
      name: "Dismiss Text"
      description: "Text to show on the dismiss button"
      default: "Dismiss"
      selector:
        text:
    dismiss_action:
      name: "Dismiss Action"
      description: "Action to run when notification is dismissed"
      default: []
      selector:
        action:
mode: restart

sequence:
  - alias: "Set up variables"
    variables:
      action_confirm: "{{ 'CONFIRM_' ~ context.id }}"
      action_dismiss: "{{ 'DISMISS_' ~ context.id }}"
  - alias: "Send notification"
    service: !input notify_device
    data:
      message: !input message 
      title: !input title
      data:
        color: !input color
        channel: !input channel
        sticky: !input sticky
        notification_icon: !input icon
        image: !input image
        importance: !input priority
        clickAction: !input 'click_action'
        ttl: 0
        actions:
          - action: "{{ action_confirm }}"
            title:  !input confirm_text
          - action: "{{ action_dismiss }}"
            title:  !input dismiss_text
        tag: !input tag
  - alias: "Awaiting response"
    wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_confirm }}"
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_dismiss }}"
      - platform: event
        event_type: mobile_app_notification_cleared
    timeout: !input timeout
  - choose:
      - conditions: '{{ wait.trigger.event.event_type == "mobile_app_notification_cleared" }}' 
        sequence: 
          - service: !input notify_device
            data:
              message: clear_notification
              data:
                tag: !input tag
          - choose:
            default: !input dismiss_action
      - conditions: "{{ wait.trigger.event.data.action == action_confirm }}"
        sequence: 
          - service: !input notify_device
            data:
              message: clear_notification
              data:
                tag: !input tag
          - choose:
            default: !input confirm_action
      - conditions: "{{ wait.trigger.event.data.action == action_dismiss }}"
        sequence: 
          - service: !input notify_device
            data:
              message: clear_notification
              data:
                tag: !input tag
          - choose:
            default: !input dismiss_action
      - conditions: "{{ wait.remaining == 0}}"
        sequence: 
          - service: !input notify_device
            data:
              message: clear_notification
              data:
                tag: !input tag
          - choose:
            default: !input dismiss_action
