blueprint:
  name: Android Actionable Notification
  description: >-
    A script that sends an actionable notification to Android devices with up to 3 actionable buttons.
  domain: script
  source_url: https://github.com/MRobi1/android-actionable-notification/blob/main/android_actionable_notification.yaml
  input:
    notify_device:
      name: Device to notify (single device)
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
    notify_group:
      name: Notification Group
      description: The name of the notification group to call. IE all_phones
      default: ''
    title:
      name: "Title"
      description: "The title of the button shown in the notification."
      default: ""
      selector:
        text:
    message:
      name: "Message"
      description: "The message body"
      selector:
        text:
    icon:
      name: (Optional) Icon
      description: MDI Icon to use for notification such as mdi:cctv Leaving blank will use the Home Assistant icon.
      default: ''
      selector:
        icon:
    color:
      name: Color
      description: Color for icon. Can be color name or hex value. Leaving blank will use the Home Assistant blue.
      default:
        - 3
        - 169
        - 244
      selector:
        color_rgb:      
    priority:
      name: Notification Priority - Android Specific
      description: Priority level for notification
      default: 'default'
      selector:
        select:
          mode: dropdown
          options:
            - high
            - low
            - max
            - min
            - default
    sticky:
      name: (Optional) Sticky - Android Specific
      description: When enabled, the notification will stay active on the device after interacting with it and remain there until cleared.
      default: false
      selector:
        boolean: {}
    channel:
      name: (Optional) Channel - Android Specific
      description: Create a new channel for notifications to allow custom notification sounds, vibration patterns and overide of Do Not Disturb mode. Configured directly on the device.
      default: ''
      selector:
        text:
    tag:
      name: "Notification Tag"
      description: "notification tag for updating and dismissing the notification"
      default: ''
      selector:
        text:
    timeout:
        name: "Timeout duration"
        default: {}
        selector:
          duration:
    image:
      name: "Image"
      description: "Path to optional image to attach with message"
      default: {}
      selector:
        text:
    click_action:
      name: Click Action
      description: What to open when the notification is clicked. Can be a URL, a relative URL to your Home Assistant instance such as /lovelace/test, or an Android application such as app://<package_name>. 
      default: ''
      selector:
        text:
# Action 1

    action_1_title:
      name: First action name
      description: Name of the first button
      default: ""
      
    action_1_uri:
      name: URI for action 1 (Optional)
      description: Optional URI for the first action
      default: ""

    first_action:
      name: Action 1
      description: "Action to run when the first action is clicked"
      default: []
      selector:
        action:

# Action 2

    action_2_title:
      name: Second action name
      description: Name of the second button
      default: ""

    action_2_uri:
      name: URI for action 1 (Optional)
      description: Optional URI for the second action
      default: ""

    second_action:
      name: Action 2
      description: Action to run when the second action is clicked"
      default: []
      selector:
        action:

# Action 3
    
    action_3_title:
      name: Third action name
      description: Name of the third button
      default: ""
      
    action_3_uri:
      name: URI for action 3 (Optional)
      description: Optional URI for the third action
      default: ""

    third_action:
      name: Action 3
      description: "Action to run when the third action is clicked"
      default: []
      selector:
        action:
mode: restart

variables:
  group_target: !input 'notify_group'
