blueprint:
  name: Confirmable Notification
  description: >-
    A script that sends an actionable notification with a confirmation before
    running the specified action.
  domain: script
  source_url: https://github.com/MRobi1/android-actionable-notification/blob/main/android_actionable_notification.yaml
  input:
    notify_device:
      name: Notification service
      description: Notification service name (ex. Notify.mobile_app_....). Note that device/s needs to run the official Home Assistant app to receive notifications.
      selector:
        text:
    title:
      name: "Title"
      description: "The title of the button shown in the notification."
      default: ""
      selector:
        text:
    message:
      name: "Message"
      description: "The message body"
      selector:
        text:
    icon:
      name: (Optional) Icon
      description: MDI Icon to use for notification such as mdi:cctv Leaving blank will use the Home Assistant icon.
      default: ''
      selector:
        icon:
    color:
      name: (Optional) Color - Android Specific
      description: Color for icon. Can be color name or hex value. Leaving blank will use the Home Assistant blue.
      default: ''     
    priority:
      name: Notification Priority - Android Specific
      description: Priority level for notification
      default: 'default'
      selector:
        select:
          mode: dropdown
          options:
            - high
            - low
            - max
            - min
            - default
    sticky:
      name: (Optional) Sticky - Android Specific
      description: When enabled, the notification will stay active on the device after interacting with it and remain there until cleared.
      default: false
      selector:
        boolean: {}
    channel:
      name: (Optional) Channel - Android Specific
      description: Create a new channel for notifications to allow custom notification sounds, vibration patterns and overide of Do Not Disturb mode. Configured directly on the device.
      default: ''
      selector:
        text:
    tag:
      name: "Notification Tag"
      description: "notification tag for updating and dismissing the notification"
      default: ''
      selector:
        text:
    timeout:
        name: "Timeout duration"
        default: {}
        selector:
          duration:
    image:
      name: "Image"
      description: "Path to optional image to attach with message"
      default: {}
      selector:
        text:
    click_action:
      name: Click Action
      description: What to open when the notification is clicked. Can be a URL, a relative URL to your Home Assistant instance such as /lovelace/test, or an Android application such as app://<package_name>. 
      default: ''
      selector:
        text:
    tag:
      name: "Notification Tag"
      description: "notification tag for updating and dismissing the notification"
      default: {}
      selector:
        text:
    timeout:
        name: "Timeout duration"
        default: {}
        selector:
          duration:        
    action1_text:
      name: "Action1 Text"
      description: "Text to show on the first action button"
      default: ""
      selector:
        text:
    action1_action:
      name: "Action1 Action"
      description: "Action to run when first action button pressed"
      default: []
      selector:
        action:
    action2_text:
      name: "Action2 Action"
      description: "Action to run when second action button pressed"
      default: ""
      selector:
        text:
    action2_action:
      name: "Action2 Action"
      description: "Action to run when first action button pressed"
      default: []
      selector:
        action:
mode: restart

sequence:
  - alias: "Set up variables"
    variables:
      action_action1: "{{ 'action1_' ~ context.id }}"
      action_action2: "{{ 'action2S_' ~ context.id }}"
  - alias: "Send notification"
    service: !input notify_device
    data:
      message: !input message 
      title: !input title
      data:
        color: !input color
        channel: !input channel
        sticky: !input sticky
        notification_icon: !input icon
        image: !input image
        importance: !input priority
        clickAction: !input 'click_action'
        ttl: 0      
        actions:
          - action: "{{ action_action1 }}"
            title:  !input action1_text
          - action: "{{ action_action2 }}"
            title:  !input action2_text
        tag: !input tag
  - alias: "Awaiting response"
    wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_action1 }}"
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_action2 }}"
      - platform: event
        event_type: mobile_app_notification_cleared
    timeout: !input timeout
  - choose:
      - conditions: '{{ wait.trigger.event.event_type == "mobile_app_notification_cleared" }}' 
        sequence: 
          - service: !input notify_device
            data:
              message: clear_notification
              data:
                tag: !input tag
          - choose:
            default: !input action2_action
      - conditions: "{{ wait.trigger.event.data.action == action_action1 }}"
        sequence: 
          - service: !input notify_device
            data:
              message: clear_notification
              data:
                tag: !input tag
          - choose:
            default: !input action2_action
      - conditions: "{{ wait.trigger.event.data.action == action_action2 }}"
        sequence: 
          - service: !input notify_device
            data:
              message: clear_notification
              data:
                tag: !input tag
          - choose:
            default: !input action2_action
      - conditions: "{{ wait.remaining == 0}}"
        sequence: 
          - service: !input notify_device
            data:
              message: clear_notification
              data:
                tag: !input tag
          - choose:
            default: !input action2_action
